spring:
  datasource:
    driver-class-name: @db.driver@
    url: @db.url@/@db.database@
    username: @db.username@
    password: @db.password@
  jpa:
    show-sql: true
client:
  url: "http://localhost:4200"
